#!/usr/bin/env bash
#
# Installs what this sandbox can actually install, so a web session can run
# checks locally instead of discovering every failure through CI.
#
# What is and isn't reachable here was measured, not assumed:
#
#   npm install               ~15s   vitest, vue-tsc, prettier, eslint
#   composer install --no-dev ~4m    a bootable app: artisan, migrations, tinker
#   dev dependencies          never  Pint, Pest, PHPStan and Larastan are all
#                                    require-dev, and every dev package's dist
#                                    URL (api.github.com zipball) returns 403
#                                    through the egress proxy. Not a phpstan
#                                    quirk: pint, pest and larastan 403 too.
#
# Both installs are idempotent and the container is cached once the hook
# finishes, so the composer cost is paid on a cold container, not every session.
# Neither failure is fatal: a session with no dependencies is exactly the
# situation this hook exists to improve on, never a reason to refuse to start.

set -uo pipefail

# Local checkouts manage their own dependencies.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
    exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0

frontend='unavailable'
backend='unavailable'

# `npm ci` rather than `npm install`: install rewrites package-lock.json here
# (this container's npm strips `libc` fields from optional deps), which would
# leave every session with a dirty tree and invite a commit that breaks CI's
# own `npm ci`. Costs ~15s against install's ~3s warm, and never mutates a
# tracked file.
if npm ci --no-audit --no-fund >/dev/null 2>&1; then
    frontend='ready'
fi

if composer install --no-dev --no-interaction --no-progress >/dev/null 2>&1; then
    backend='ready'

    # Wayfinder's action/route files are gitignored and normally generated by
    # the vite plugin at build time. Without them eslint mis-sorts every
    # `@/actions/...` import and reports import/order errors that CI does not
    # have — phantom failures are worse than no linter at all.
    php artisan wayfinder:generate >/dev/null 2>&1 || backend='ready (wayfinder generation failed; @/actions imports will mis-lint)'
fi

# SessionStart stdout becomes session context. Keep it to the two facts that
# change how the session works, since every session pays to read them.
cat <<SUMMARY
Local tooling — frontend (vitest, vue-tsc, prettier, eslint): ${frontend}. App (artisan, migrations): ${backend}.
Pint, Pest, PHPStan and Larastan cannot be installed in this sandbox (dev dists are 403 via the egress proxy) — read those from CI. Everything else runs locally; don't push to find out.
SUMMARY

exit 0
